"use client";
import Image from "next/image";
import { ArrowUpRight, Code2, Layers3, Sparkles, Globe2 } from "lucide-react";
import { motion, useInView } from "framer-motion";
import { useEffect, useRef, useState } from "react";

const proof=[["16","Years Old",Sparkles],["AI","Startup Builder",Layers3],["UI","Frontend Developer",Code2],["PK","Based in Pakistan",Globe2]] as const;
function Count({value}:{value:string}){const ref=useRef<HTMLSpanElement>(null);const inView=useInView(ref,{once:true});const [shown,setShown]=useState(value==="16"?"0":value);useEffect(()=>{if(value!=="16"||!inView)return;let frame=0;const start=performance.now();const tick=(now:number)=>{const n=Math.min(16,Math.round((now-start)/700*16));setShown(String(n));if(n<16)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[inView,value]);return <span ref={ref}>{shown}</span>}
export function About(){return <section id="about" className="relative overflow-hidden border-b border-[#272521] bg-[#0a0a09] px-5 py-24 sm:px-[7.4vw] sm:py-36"><div className="pointer-events-none absolute left-[18%] top-24 h-[34rem] w-[34rem] rounded-full bg-[#d9c7a5]/[.035] blur-[120px]"/><div className="relative mx-auto max-w-[1440px]"><div className="grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-start lg:gap-16"><div><p className="mb-8 font-mono text-[10px] tracking-[.22em] text-[#d4c6ad]">01 — ABOUT FUNIC X</p><motion.h2 initial={{opacity:0,y:35,filter:"blur(8px)"}} whileInView={{opacity:1,y:0,filter:"blur(0px)"}} viewport={{once:true,amount:.35}} transition={{duration:.9,ease:[.22,1,.36,1]}} className="max-w-3xl font-serif text-[clamp(3.3rem,7vw,7.5rem)] leading-[.88] tracking-[-.075em] text-[#eee3d1]">Building AI Products That Feel <em className="font-normal text-[#cbb895]">Premium.</em></motion.h2><div className="mt-12 max-w-md border-l border-[#cbb895]/60 pl-6"><p className="font-mono text-[10px] tracking-[.2em] text-[#cbb895]">FOUNDER STORY</p><p className="mt-5 text-[15px] leading-7 text-[#b7b0a4]">I’m Funic X — a young builder with a practical obsession: turning sharp ideas into useful, considered digital products. I care about the small decisions that make technology feel human.</p><a className="group mt-7 inline-flex items-center gap-2 font-mono text-[10px] tracking-[.15em] text-[#eee3d1]" href="#contact">LET’S BUILD TOGETHER <ArrowUpRight className="h-4 w-4 transition-transform duration-300 group-hover:-translate-y-1 group-hover:translate-x-1"/></a></div></div><motion.div initial={{opacity:0,scale:.96}} whileInView={{opacity:1,scale:1}} viewport={{once:true,amount:.25}} transition={{duration:1.05,ease:[.22,1,.36,1]}} className="group relative aspect-[4/5] overflow-hidden rounded-sm border border-[#cbb895]/40 bg-[#161411] shadow-[0_30px_90px_rgba(0,0,0,.35)]"><Image src="/about-funicx.png" alt="Funic X founder portrait in warm cinematic light" fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover object-[76%_50%] transition-transform duration-[1.4s] ease-out group-hover:scale-[1.035]"/><div className="absolute inset-0 bg-gradient-to-t from-black/35 via-transparent to-transparent"/></motion.div></div><div className="mt-20 grid border-y border-[#373229] sm:grid-cols-2 lg:grid-cols-4">{proof.map(([value,label,Icon],index)=><motion.div key={label} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.09}} className="flex min-h-32 items-center gap-4 border-[#373229] px-0 py-7 sm:px-6 sm:odd:border-l lg:border-l lg:first:border-l-0"><Icon className="h-4 w-4 text-[#cbb895]"/><p className="text-sm text-[#a9a197]"><b className="mr-1 font-serif text-2xl font-normal text-[#e9dcc5]"><Count value={value}/></b>{label}</p></motion.div>)}</div></div></section>}
